// import shirt from "./images/img1.jpg";

export default {
  products: [
    {
      _id: 1,
      name: "Slime Shirt",
      image: "/images/img1.jpg",
      price: 350,
      brand: "Nike",
      rating: 5.5,
      numReview: 10,
      description: "Washable with nice color",
      inStockItems: 4,
    },
    {
      _id: 2,
      name: "Casual Shirt",
      image: "/images/img1.jpg",
      price: 350,
      brand: "Nike",
      rating: 5.5,
      numReview: 10,
      description: "Washable with nice color",
      inStockItems: 3,
    },
    {
      _id: 3,
      name: "Fit Shirt",
      image: "/images/img1.jpg",
      price: 350,
      brand: "Nike",
      rating: 5.5,
      numReview: 10,
      description: "Washable with nice color",
      inStockItems: 1,
    },
    {
      _id: 4,
      name: "Slime Shirt",
      image: "/images/img1.jpg",
      price: 350,
      brand: "Nike",
      rating: 5.5,
      numReview: 10,
      description: "Washable with nice color",
      inStockItems: 2,
    },
    {
      _id: 5,
      name: "Casual Shirt",
      image: "/images/img1.jpg",
      price: 350,
      brand: "Nike",
      rating: 5.5,
      numReview: 10,
      description: "Washable with nice color",
      inStockItems: 8,
    },
    {
      _id: 6,
      name: "Fit Shirt",
      image: "/images/img1.jpg",
      price: 350,
      brand: "Nike",
      rating: 5.5,
      numReview: 10,
      description: "Washable with nice color",
      inStockItems: 6,
    },
  ],
};
